export class DataSpCitiesModule {
    static cidadesSp = [
      'Adamantina', 'Adolfo', 'Aguaí', 'Águas da Prata', 'Águas de Lindóia', 'Alambari', 'Alfredo Marcondes', 'Altair', 'Altinópolis', 'Alumínio', 
      'Álvares Florence', 'Álvares Machado', 'Andradina', 'Angatuba', 'Anhembi', 'Anhumas', 'Aparecida', 'Aparecida d\'Oeste', 'Aramina', 'Arandu',
      'Arapeí', 'Araraquara', 'Araras', 'Arco-Íris', 'Arealva', 'Areias', 'Arenápolis', 'Arujá', 'Aspásia', 'Assis', 'Atibaia', 'Auriflama', 
      'Avaré', 'Bady Bassitt', 'Balbinos', 'Bálsamo', 'Bananal', 'Barão de Antonina', 'Bariri', 'Barra Bonita', 'Barra do Chapéu', 'Barra do Turvo', 
      'Barretos', 'Bastos', 'Bauru', 'Bebedouro', 'Bento de Abreu', 'Bertioga', 'Bilac', 'Birigüi', 'Bocaina', 'Bofete', 'Boituva', 'Bom Jesus dos Perdões', 
      'Bom Sucesso de Itararé', 'Borá', 'Boracéia', 'Borborema', 'Brazópolis', 'Bragança Paulista', 'Biritiba-Mirim', 'Cabreúva', 'Caconde', 'Cafelândia', 
      'Caiabu', 'Caieiras', 'Cajamar', 'Cajati', 'Cajuru', 'Campinas', 'Campo Limpo Paulista', 'Campos do Jordão', 'Campos Novos Paulista', 'Cananéia', 
      'Cândido Motta', 'Capela do Alto', 'Capivari', 'Caraguatatuba', 'Carapicuíba', 'Cardoso', 'Casa Branca', 'Cássia dos Coqueiros', 'Castilho', 'Catanduva', 
      'Catiguá', 'Cedral', 'Cerqueira César', 'Cerquilho', 'César de Souza', 'Charqueada', 'Chavantes', 'Clementina', 'Colina', 'Colômbia', 'Conchal', 
      'Conchas', 'Cordeirópolis', 'Coroados', 'Coronel Macedo', 'Corumbataí', 'Cosmorama', 'Cotia', 'Cravinhos', 'Cristais Paulista', 'Cubatão', 'Cunha', 
      'Descalvado', 'Diadema', 'Dirce Reis', 'Divinolândia', 'Dobrada', 'Doresópolis', 'Dourado', 'Dracena', 'Duartina', 'Dumont', 'Echaporã', 'Eldorado', 
      'Elias Fausto', 'Elisiário', 'Embu das Artes', 'Embu-Guaçu', 'Engenheiro Coelho', 'Espírito Santo do Pinhal', 'Espírito Santo do Turvo', 'Estiva Gerbi', 
      'Estrela d\'Oeste', 'Euclides da Cunha Paulista', 'Fartura', 'Fernando Prestes', 'Fernandópolis', 'Fernão', 'Flórida Paulista', 'Floreal', 'Flórida Paulista',
      'Franca', 'Gabriel Monteiro', 'Gália', 'Garça', 'Gastão Vidigal', 'Gavião Peixoto', 'General Salgado', 'Getulina', 'Glicério', 'Guapiara', 'Guaraci', 
      'Guariba', 'Guarujá', 'Guarulhos', 'Guatapará', 'Guaíra', 'Guaíba', 'Herculândia', 'Holambra', 'Iacanga', 'Ibaté', 'Ibiporanga', 'Ibiúna', 'Icém', 
      'Iepê', 'Igaraçu do Tietê', 'Iguape', 'Ilha Comprida', 'Ilhabela', 'Indaiatuba', 'Itaí', 'Itaberá', 'Itápolis', 'Itapecerica da Serra', 'Itapetininga', 
      'Itapeva', 'Itapira', 'Itapuí', 'Itapura', 'Itaquaquecetuba', 'Itararé', 'Itariri', 'Itatiba', 'Itatinga', 'Itirapina', 'Itirapuã', 'Itu', 'Itupeva', 
      'Itinga', 'Ivacan', 'Ivoti', 'Jaboticabal', 'Jales', 'Jambeiro', 'Jandira', 'Jarinu', 'Jaú', 'Joanópolis', 'José Bonifácio', 'José dos Campos', 
      'Júlio Mesquita', 'Jundiaí', 'Junqueirópolis', 'Juquitiba', 'Laranjal Paulista', 'Leme', 'Lençóis Paulista', 'Limeira', 'Lindóia', 'Lins', 'Lorena', 
      'Luís Antônio', 'Luiziânia', 'Macatuba', 'Macaubal', 'Mairinque', 'Mairiporã', 'Manduri', 'Marabá Paulista', 'Marília', 'Marinópolis', 'Matão', 
      'Mauá', 'Mendonça', 'Meridiano', 'Mesópolis', 'Miguelópolis', 'Mira Estrela', 'Mogi das Cruzes', 'Mogi Guaçu', 'Mogi Mirim', 'Mombuca', 'Monções', 
      'Morro Agudo', 'Morungaba', 'Motuca', 'Murutinga do Sul', 'Nantes', 'Narandiba', 'Natividade da Serra', 'Nipoã', 'Nova Aliança', 'Nova Campina', 
      'Nova Canaã Paulista', 'Nova Castilho', 'Nova Granada', 'Nova Luzitânia', 'Nova Odessa', 'Novo Horizonte', 'Olímpia', 'Onda Verde', 'Orindiúva', 
      'Orlândia', 'Osasco', 'Ourinhos', 'Ouro Verde', 'Pacaembu', 'Palmeira d\'Oeste', 'Palmeiras de Goiás', 'Palmital', 'Panorama', 'Paraguaçu Paulista',
      'Paranapanema', 'Parapuã', 'Pardinho', 'Pariquera-Açu', 'Pederneiras', 'Pedra Bela', 'Pedrinhas Paulista', 'Penápolis', 'Peruíbe', 'Piedade', 
      'Pilar do Sul', 'Pindamonhangaba', 'Pindorama', 'Pinhalzinho', 'Piracaia', 'Piracicaba', 'Pirapora do Bom Jesus', 'Pirapozinho', 'Pirassununga', 
      'Poá', 'Poloni', 'Pompeia', 'Pongaíba', 'Pontal', 'Ponte Alta', 'Porangaba', 'Porto Feliz', 'Porto Ferreira', 'Potim', 'Pracinha', 'Promissão', 
      'Quadra', 'Quatá', 'Queiroz', 'Redenção da Serra', 'Regente Feijó', 'Ribeirão Bonito', 'Ribeirão Branco', 'Ribeirão Corrente', 'Ribeirão do Sul', 
      'Ribeirão Preto', 'Riversul', 'Rocinha', 'Rosana', 'Rubiácea', 'Rufino', 'Sabino', 'Salgado Filho', 'Sales', 'Salesópolis', 'Saltinho', 'Salto', 
      'Salto de Pirapora', 'San Marcos', 'Santo André', 'Santo Anastácio', 'Santo Antônio da Alegria', 'Santo Antônio do Jardim', 'Santos', 'São Bento do Sapucaí',
      'São Bernardo do Campo', 'São Caetano do Sul', 'São João da Boa Vista', 'São João de Iracema', 'São Joaquim da Barra', 'São José da Bela Vista',
      'São José do Barreiro', 'São José dos Campos', 'São Lourenço da Serra', 'São Luís do Paraitinga', 'São Manuel', 'São Miguel Arcanjo', 'São Paulo', 
      'São Pedro', 'São Roque', 'São Sebastião', 'São Simão', 'Sarapuí', 'Sarutaiá', 'Serrana', 'Serra Negra', 'Sertãozinho', 'Silveiras', 'Socorro', 
      'Sodrelândia', 'Sorocaba', 'Sud Mennucci', 'Sumaré', 'Suzano', 'Tabapuã', 'Taboão da Serra', 'Taciba', 'Tambaú', 'Tanabi', 'Tapiraí', 'Taquaral', 
      'Taquaritinga', 'Taubaté', 'Teodoro Sampaio', 'Terra Roxa', 'Tietê', 'Tremembé', 'Tupi Paulista', 'Ubarana', 'Ubatuba', 'Ubirajara', 'Uchoa', 
      'União Paulista', 'Urânia', 'Urupês', 'Valentim Gentil', 'Valinhos', 'Valparaíso', 'Vargem', 'Vargem Grande do Sul', 'Várzea Paulista', 'Vera Cruz',
      'Vinhedo', 'Viradouro', 'Vista Alegre do Alto', 'Votuporanga'
    ];
  }
  